name: fork-image

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "0 0 * * *"

jobs:
  pull-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWD }}

      - name: Pull the image and push re-tagged image
        run: |
          docker pull dqzboy/mirror-hub:latest
          docker tag dqzboy/mirror-hub:latest ${{ secrets.DOCKERHUB_USERNAME }}/mirror-hub:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mirror-hub:latest
